package com.system.modals.modal;

// default package
// Generated Jan 30, 2023, 2:34:39 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StoreSummaryLogs generated by hbm2java
 */
@Entity
@Table(name = "store_summary_logs", schema = "dbo")
public class StoreSummaryLogs implements java.io.Serializable {

	private Integer rowId;
	private String productName;
	private Integer productId;
	private Integer totalQuantity;
	private Date snapshotDate;

	public StoreSummaryLogs() {
	}

	public StoreSummaryLogs(String productName, Integer productId, Integer totalQuantity, Date snapshotDate) {
		this.productName = productName;
		this.productId = productId;
		this.totalQuantity = totalQuantity;
		this.snapshotDate = snapshotDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "product_name", length = 50)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_id")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "total_quantity")
	public Integer getTotalQuantity() {
		return this.totalQuantity;
	}

	public void setTotalQuantity(Integer totalQuantity) {
		this.totalQuantity = totalQuantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "snapshot_date", length = 23)
	public Date getSnapshotDate() {
		return this.snapshotDate;
	}

	public void setSnapshotDate(Date snapshotDate) {
		this.snapshotDate = snapshotDate;
	}

}
