package com.system.modals.modal;

// default package
// Generated Jun 16, 2022, 12:36:38 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.Data;

/**
 * TblAdminUsers generated by hbm2java
 */
@Data
@Entity
@Table(name = "TBL_ADMIN_USERS", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = "admin_user_name"))
public class TblAdminUsersBk implements java.io.Serializable {

	private Integer adminUserId;
	private String adminUserName;
	private String adminUserPassword;
	private String adminUserEmail;
	private String adminUserFullname;
	private char adminUserStatus;
	private String bcryptPassword;

	public TblAdminUsersBk() {
	}

	public TblAdminUsersBk(String adminUserName, String adminUserPassword, String adminUserEmail,
			String adminUserFullname, Character adminUserStatus) {
		this.adminUserName = adminUserName;
		this.adminUserPassword = adminUserPassword;
		this.adminUserEmail = adminUserEmail;
		this.adminUserFullname = adminUserFullname;
		this.adminUserStatus = adminUserStatus;
	}

	public TblAdminUsersBk(String adminUserName, String adminUserPassword, String adminUserEmail,
			String adminUserFullname, Character adminUserStatus, String bcryptPassword) {
		this.adminUserName = adminUserName;
		this.adminUserPassword = adminUserPassword;
		this.adminUserEmail = adminUserEmail;
		this.adminUserFullname = adminUserFullname;
		this.adminUserStatus = adminUserStatus;
		this.bcryptPassword = bcryptPassword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "admin_user_id", unique = true, nullable = false)
	public Integer getAdminUserId() {
		return this.adminUserId;
	}

	public void setAdminUserId(Integer adminUserId) {
		this.adminUserId = adminUserId;
	}

	@Column(name = "admin_user_name", columnDefinition = "nvarchar",unique = true, nullable = false)	
	public String getAdminUserName() {
		return this.adminUserName;
	}

	public void setAdminUserName(String adminUserName) {
		this.adminUserName = adminUserName;
	}

	@Column(name = "admin_user_password", columnDefinition = "nvarchar",nullable = false)	
	public String getAdminUserPassword() {
		return this.adminUserPassword;
	}

	public void setAdminUserPassword(String adminUserPassword) {
		this.adminUserPassword = adminUserPassword;
	}

	@Column(name = "admin_user_email", columnDefinition = "nvarchar",nullable = false)
	public String getAdminUserEmail() {
		return this.adminUserEmail;
	}

	public void setAdminUserEmail(String adminUserEmail) {
		this.adminUserEmail = adminUserEmail;
	}

	@Column(name = "admin_user_fullname", columnDefinition = "nvarchar",nullable = false)
	public String getAdminUserFullname() {
		return this.adminUserFullname;
	}

	public void setAdminUserFullname(String adminUserFullname) {
		this.adminUserFullname = adminUserFullname;
	}

	@Column(name = "admin_user_status", nullable = false, length = 1)
	public char getAdminUserStatus() {
		return this.adminUserStatus;
	}

	public void setAdminUserStatus(char adminUserStatus) {
		this.adminUserStatus = adminUserStatus;
	}

	@Column(name = "bcrypt_password",columnDefinition = "nvarchar")
	public String getBcryptPassword() {
		return this.bcryptPassword;
	}

	public void setBcryptPassword(String bcryptPassword) {
		this.bcryptPassword = bcryptPassword;
	}

}
