package com.system.modals.modal;

// default package
// Generated Jun 12, 2022, 5:31:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import lombok.Data;

/**
 * TblCardTypeDetails generated by hbm2java
 */
@Data
@Entity
@Table(name = "TBL_CARD_TYPE_DETAILS", schema = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = "CARD_CODE"))
public class TblCardTypeDetails implements java.io.Serializable {

	private Integer rowId;
	private String cardCode;
	private Integer amount;
	private Integer partnerCardId;
	private Integer minLimit;
	private Integer maxLimit;
	private Integer autoDownload;
	private Integer alertLimit;
	private Integer isAlert;
	private Date latestUpdate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LATEST_UPDATE", length = 23)
	public Date getLatestUpdate() {
		return this.latestUpdate;
	}

	public void setLatestUpdate(Date latestUpdate) {
		this.latestUpdate = latestUpdate;
	}
	
	
	public TblCardTypeDetails() {
	}

	public TblCardTypeDetails(String cardCode) {
		this.cardCode = cardCode;
	}

	public TblCardTypeDetails(String cardCode, Integer amount, Integer partnerCardId, Integer minLimit,
			Integer maxLimit, Integer autoDownload, Integer alertLimit, Integer isAlert,Date latestUpdate) {
		this.cardCode = cardCode;
		this.amount = amount;
		this.partnerCardId = partnerCardId;
		this.minLimit = minLimit;
		this.maxLimit = maxLimit;
		this.autoDownload = autoDownload;
		this.alertLimit = alertLimit;
		this.isAlert = isAlert;
		this.latestUpdate = latestUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ROW_ID", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@NotNull
	@Column(name = "CARD_CODE", nullable = false, length = 50)
	public String getCardCode() {
		return this.cardCode;
	}

	public void setCardCode(String cardCode) {
		this.cardCode = cardCode;
	}

	@NotNull
	@Min(value = 1)
	@Column(name = "AMOUNT")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@NotNull
	@Column(name = "PARTNER_CARD_ID")
	public Integer getPartnerCardId() {
		return this.partnerCardId;
	}

	public void setPartnerCardId(Integer partnerCardId) {
		this.partnerCardId = partnerCardId;
	}

	@NotNull
	@Min(value = 1)
	@Column(name = "MIN_LIMIT")
	public Integer getMinLimit() {
		return this.minLimit;
	}

	public void setMinLimit(Integer minLimit) {
		this.minLimit = minLimit;
	}

	@NotNull
	@Min(value = 1)
	@Column(name = "MAX_LIMIT")
	public Integer getMaxLimit() {
		return this.maxLimit;
	}

	public void setMaxLimit(Integer maxLimit) {
		this.maxLimit = maxLimit;
	}

	@Column(name = "AUTO_DOWNLOAD")
	public Integer getAutoDownload() {
		return this.autoDownload;
	}

	public void setAutoDownload(Integer autoDownload) {
		this.autoDownload = autoDownload;
	}

	@Column(name = "ALERT_LIMIT")
	public Integer getAlertLimit() {
		return this.alertLimit;
	}

	public void setAlertLimit(Integer alertLimit) {
		this.alertLimit = alertLimit;
	}

	@Column(name = "IS_ALERT")
	public Integer getIsAlert() {
		return this.isAlert;
	}
	
	public void setIsAlert(Integer isAlert) {
		this.isAlert = isAlert;
	}
		
}
