package com.system.modals.modal;

// default package
// Generated Sep 28, 2022, 5:22:52 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMerchantBalanceLogs generated by hbm2java
 */
@Entity
@Table(name = "TBL_MERCHANT_BALANCE_LOGS", schema = "dbo")
public class TblMerchantBalanceLogs implements java.io.Serializable {

	private Integer merchantBalanceLogId;
	private int merchantId;
	private long merchantBalanceInitialAmount;
	private long merchantBalanceFinalAmount;
	private int merchantBalanceChangeType;
	private long merchantBalanceChangeAmount;
	private Serializable merchantBalanceChangeRemark;
	private int registerPerson;
	private Date registerDatetime;
	private char channel;
	private char registerBy;
	private Serializable remark;
	private String objectId;

	public TblMerchantBalanceLogs() {
	}

	public TblMerchantBalanceLogs(int merchantId, long merchantBalanceInitialAmount, long merchantBalanceFinalAmount,
			int merchantBalanceChangeType, long merchantBalanceChangeAmount, Serializable merchantBalanceChangeRemark,
			int registerPerson, Date registerDatetime, char channel, char registerBy) {
		this.merchantId = merchantId;
		this.merchantBalanceInitialAmount = merchantBalanceInitialAmount;
		this.merchantBalanceFinalAmount = merchantBalanceFinalAmount;
		this.merchantBalanceChangeType = merchantBalanceChangeType;
		this.merchantBalanceChangeAmount = merchantBalanceChangeAmount;
		this.merchantBalanceChangeRemark = merchantBalanceChangeRemark;
		this.registerPerson = registerPerson;
		this.registerDatetime = registerDatetime;
		this.channel = channel;
		this.registerBy = registerBy;
	}

	public TblMerchantBalanceLogs(int merchantId, long merchantBalanceInitialAmount, long merchantBalanceFinalAmount,
			int merchantBalanceChangeType, long merchantBalanceChangeAmount, Serializable merchantBalanceChangeRemark,
			int registerPerson, Date registerDatetime, char channel, char registerBy, Serializable remark,
			String objectId) {
		this.merchantId = merchantId;
		this.merchantBalanceInitialAmount = merchantBalanceInitialAmount;
		this.merchantBalanceFinalAmount = merchantBalanceFinalAmount;
		this.merchantBalanceChangeType = merchantBalanceChangeType;
		this.merchantBalanceChangeAmount = merchantBalanceChangeAmount;
		this.merchantBalanceChangeRemark = merchantBalanceChangeRemark;
		this.registerPerson = registerPerson;
		this.registerDatetime = registerDatetime;
		this.channel = channel;
		this.registerBy = registerBy;
		this.remark = remark;
		this.objectId = objectId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "merchant_balance_log_id", unique = true, nullable = false)
	public Integer getMerchantBalanceLogId() {
		return this.merchantBalanceLogId;
	}

	public void setMerchantBalanceLogId(Integer merchantBalanceLogId) {
		this.merchantBalanceLogId = merchantBalanceLogId;
	}

	@Column(name = "merchant_id", nullable = false)
	public int getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(int merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "merchant_balance_initial_amount", nullable = false)
	public long getMerchantBalanceInitialAmount() {
		return this.merchantBalanceInitialAmount;
	}

	public void setMerchantBalanceInitialAmount(long merchantBalanceInitialAmount) {
		this.merchantBalanceInitialAmount = merchantBalanceInitialAmount;
	}

	@Column(name = "merchant_balance_final_amount", nullable = false)
	public long getMerchantBalanceFinalAmount() {
		return this.merchantBalanceFinalAmount;
	}

	public void setMerchantBalanceFinalAmount(long merchantBalanceFinalAmount) {
		this.merchantBalanceFinalAmount = merchantBalanceFinalAmount;
	}

	@Column(name = "merchant_balance_change_type", nullable = false)
	public int getMerchantBalanceChangeType() {
		return this.merchantBalanceChangeType;
	}

	public void setMerchantBalanceChangeType(int merchantBalanceChangeType) {
		this.merchantBalanceChangeType = merchantBalanceChangeType;
	}

	@Column(name = "merchant_balance_change_amount", nullable = false)
	public long getMerchantBalanceChangeAmount() {
		return this.merchantBalanceChangeAmount;
	}

	public void setMerchantBalanceChangeAmount(long merchantBalanceChangeAmount) {
		this.merchantBalanceChangeAmount = merchantBalanceChangeAmount;
	}

	@Column(name = "merchant_balance_change_remark", nullable = false)
	public Serializable getMerchantBalanceChangeRemark() {
		return this.merchantBalanceChangeRemark;
	}

	public void setMerchantBalanceChangeRemark(Serializable merchantBalanceChangeRemark) {
		this.merchantBalanceChangeRemark = merchantBalanceChangeRemark;
	}

	@Column(name = "register_person", nullable = false)
	public int getRegisterPerson() {
		return this.registerPerson;
	}

	public void setRegisterPerson(int registerPerson) {
		this.registerPerson = registerPerson;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_datetime", nullable = false, length = 23)
	public Date getRegisterDatetime() {
		return this.registerDatetime;
	}

	public void setRegisterDatetime(Date registerDatetime) {
		this.registerDatetime = registerDatetime;
	}

	@Column(name = "CHANNEL", nullable = false, length = 1)
	public char getChannel() {
		return this.channel;
	}

	public void setChannel(char channel) {
		this.channel = channel;
	}

	@Column(name = "REGISTER_BY", nullable = false, length = 1)
	public char getRegisterBy() {
		return this.registerBy;
	}

	public void setRegisterBy(char registerBy) {
		this.registerBy = registerBy;
	}

	@Column(name = "remark")
	public Serializable getRemark() {
		return this.remark;
	}

	public void setRemark(Serializable remark) {
		this.remark = remark;
	}

	@Column(name = "objectId", length = 50)
	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

}
