package com.system.modals.modal;



import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.annotation.Persistent;

/**
 * TopupListFiles generated by hbm2java
 */
@Persistent
@Entity
@Table(name = "topup_list_files", schema = "dbo")
public class TopupListFiles implements java.io.Serializable {

	private Long rowId;
	private String fileUpload;
	private String merchantUsername;
	private Date createdDate;
	private Date approvedRejectDate;
	private String approvedRejectByAdmin;
	private int identifyStatus;
	private Integer finalStatus;
	private Date latestUpdate;
	private String paymentPassword;

	public TopupListFiles() {
	}

	public TopupListFiles(String fileUpload, String merchantUsername, int identifyStatus) {
		this.fileUpload = fileUpload;
		this.merchantUsername = merchantUsername;
		this.identifyStatus = identifyStatus;
	}

	public TopupListFiles(String fileUpload, String merchantUsername, Date createdDate,
			Date approvedRejectDate, String approvedRejectByAdmin, int identifyStatus, Integer finalStatus,
			Date latestUpdate) {
		this.fileUpload = fileUpload;
		this.merchantUsername = merchantUsername;
		this.createdDate = createdDate;
		this.approvedRejectDate = approvedRejectDate;
		this.approvedRejectByAdmin = approvedRejectByAdmin;
		this.identifyStatus = identifyStatus;
		this.finalStatus = finalStatus;
		this.latestUpdate = latestUpdate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false, precision = 0)
	public Long getRowId() {
		return this.rowId;
	}

	public void setRowId(Long rowId) {
		this.rowId = rowId;
	}

	@Column(name = "file_upload", nullable = false)
	public String getFileUpload() {
		return this.fileUpload;
	}

	public void setFileUpload(String fileUpload) {
		this.fileUpload = fileUpload;
	}

	@Column(name = "merchant_username", nullable = false)
	public String getMerchantUsername() {
		return this.merchantUsername;
	}

	public void setMerchantUsername(String merchantUsername) {
		this.merchantUsername = merchantUsername;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23, insertable = false)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approved_reject_date", length = 23)
	public Date getApprovedRejectDate() {
		return this.approvedRejectDate;
	}

	public void setApprovedRejectDate(Date approvedRejectDate) {
		this.approvedRejectDate = approvedRejectDate;
	}

	@Column(name = "approved_reject_by_admin")
	public String getApprovedRejectByAdmin() {
		return this.approvedRejectByAdmin;
	}

	public void setApprovedRejectByAdmin(String approvedRejectByAdmin) {
		this.approvedRejectByAdmin = approvedRejectByAdmin;
	}

	@Column(name = "identify_status", nullable = false, insertable = false)
	public int getIdentifyStatus() {
		return this.identifyStatus;
	}

	public void setIdentifyStatus(int identifyStatus) {
		this.identifyStatus = identifyStatus;
	}

	@Column(name = "final_status")
	public Integer getFinalStatus() {
		return this.finalStatus;
	}

	public void setFinalStatus(Integer finalStatus) {
		this.finalStatus = finalStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "latest_update", length = 23)
	public Date getLatestUpdate() {
		return this.latestUpdate;
	}

	public void setLatestUpdate(Date latestUpdate) {
		this.latestUpdate = latestUpdate;
	}

	@Column(name = "payment_password")
	public String getPaymentPassword() {
		return paymentPassword;
	}

	public void setPaymentPassword(String paymentPassword) {
		this.paymentPassword = paymentPassword;
	}

	
}
