package com.system.modals.modal;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TopupListFileDetails generated by hbm2java
 */
@Entity
@Table(name = "topup_list_file_details", schema = "dbo")
public class TopupListFileDetails implements java.io.Serializable {

	private Integer rowId;
	private Integer fileListId;
	private String targetAccount;
	private Integer requestAmt;
	private Date createdDate;
	private String provider;
	private Integer topupStatus;
	private Date updateDate;

	public TopupListFileDetails() {
	}

	public TopupListFileDetails(Integer fileListId, String targetAccount, Integer requestAmt, 
			String provider) {
		this.fileListId = fileListId;
		this.targetAccount = targetAccount;
		this.requestAmt = requestAmt;		
		this.provider = provider;		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false, insertable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "file_list_id")
	public Integer getFileListId() {
		return this.fileListId;
	}

	public void setFileListId(Integer fileListId) {
		this.fileListId = fileListId;
	}

	@Column(name = "target_account")
	public String getTargetAccount() {
		return this.targetAccount;
	}

	public void setTargetAccount(String targetAccount) {
		this.targetAccount = targetAccount;
	}

	@Column(name = "request_amt")
	public Integer getRequestAmt() {
		return this.requestAmt;
	}

	public void setRequestAmt(Integer requestAmt) {
		this.requestAmt = requestAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23, insertable = false)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "provider")
	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	@Column(name = "topup_status")
	public Integer getTopupStatus() {
		return this.topupStatus;
	}

	public void setTopupStatus(Integer topupStatus) {
		this.topupStatus = topupStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 23)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
