package com.system.modals.modal;

// default package
// Generated Apr 23, 2023, 5:31:37 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrackingCodeData generated by hbm2java
 */
@Entity
@Table(name = "tracking_code_data", schema = "dbo")
public class TrackingCodeData implements java.io.Serializable {

	private Integer stateId;
	private String trackingCode;
	private String trackingCodeLongDesc;
	private Date createdDate;

	public TrackingCodeData() {
	}

	public TrackingCodeData(String trackingCode, String trackingCodeLongDesc, Date createdDate) {
		this.trackingCode = trackingCode;
		this.trackingCodeLongDesc = trackingCodeLongDesc;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "state_id", unique = true, nullable = false)
	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	@Column(name = "tracking_code", length = 50)
	public String getTrackingCode() {
		return this.trackingCode;
	}

	public void setTrackingCode(String trackingCode) {
		this.trackingCode = trackingCode;
	}

	@Column(name = "tracking_code_long_desc")
	public String getTrackingCodeLongDesc() {
		return this.trackingCodeLongDesc;
	}

	public void setTrackingCodeLongDesc(String trackingCodeLongDesc) {
		this.trackingCodeLongDesc = trackingCodeLongDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
