package com.system.modals.billing;

// default package
// Generated Jun 27, 2022, 12:07:54 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillTransaction generated by hbm2java
 */
@Entity
@Table(name = "bill_transaction", schema = "dbo")
public class BillTransaction implements java.io.Serializable {

	private Long rowId;
	private String targetNumber;
	private int topupAmount;
	private Date createdDate;
	private Date responseDate;
	private String refTopupAmount;
	private Integer responseStatus;
	private String partnerResponseStatus;
	private Date updatePendingAt;
	private String updatePendingRpStatus;
	private String fromIp;
	private String clientReqId;
	private String partnerReqId;
	private String providerCode;
	private String partnerFullBodyRp;
	private Integer merchantId;
	private String merchantUsername;

	public BillTransaction() {
	}

	public BillTransaction(String targetNumber, int topupAmount, String clientReqId, String partnerReqId) {
		this.targetNumber = targetNumber;
		this.topupAmount = topupAmount;
		this.clientReqId = clientReqId;
		this.partnerReqId = partnerReqId;
	}

	public BillTransaction(String targetNumber, int topupAmount, Date createdDate, Date responseDate,
			String refTopupAmount, Integer responseStatus, String partnerResponseStatus, Date updatePendingAt,
			String updatePendingRpStatus, String fromIp, String clientReqId, String partnerReqId, String providerCode,
			String partnerFullBodyRp, Integer merchantId, String merchantUsername) {
		this.targetNumber = targetNumber;
		this.topupAmount = topupAmount;
		this.createdDate = createdDate;
		this.responseDate = responseDate;
		this.refTopupAmount = refTopupAmount;
		this.responseStatus = responseStatus;
		this.partnerResponseStatus = partnerResponseStatus;
		this.updatePendingAt = updatePendingAt;
		this.updatePendingRpStatus = updatePendingRpStatus;
		this.fromIp = fromIp;
		this.clientReqId = clientReqId;
		this.partnerReqId = partnerReqId;
		this.providerCode = providerCode;
		this.partnerFullBodyRp = partnerFullBodyRp;
		this.merchantId = merchantId;
		this.merchantUsername = merchantUsername;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "row_id", unique = true, nullable = false)
	public Long getRowId() {
		return this.rowId;
	}

	public void setRowId(Long rowId) {
		this.rowId = rowId;
	}

	@Column(name = "target_number", nullable = false, length = 50)
	public String getTargetNumber() {
		return this.targetNumber;
	}

	public void setTargetNumber(String targetNumber) {
		this.targetNumber = targetNumber;
	}

	@Column(name = "topup_amount", nullable = false)
	public int getTopupAmount() {
		return this.topupAmount;
	}

	public void setTopupAmount(int topupAmount) {
		this.topupAmount = topupAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "response_date", length = 23)
	public Date getResponseDate() {
		return this.responseDate;
	}

	public void setResponseDate(Date responseDate) {
		this.responseDate = responseDate;
	}

	@Column(name = "ref_topup_amount", length = 50)
	public String getRefTopupAmount() {
		return this.refTopupAmount;
	}

	public void setRefTopupAmount(String refTopupAmount) {
		this.refTopupAmount = refTopupAmount;
	}

	@Column(name = "response_status")
	public Integer getResponseStatus() {
		return this.responseStatus;
	}

	public void setResponseStatus(Integer responseStatus) {
		this.responseStatus = responseStatus;
	}

	@Column(name = "partner_response_status", length = 50)
	public String getPartnerResponseStatus() {
		return this.partnerResponseStatus;
	}

	public void setPartnerResponseStatus(String partnerResponseStatus) {
		this.partnerResponseStatus = partnerResponseStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_pending_at", length = 23)
	public Date getUpdatePendingAt() {
		return this.updatePendingAt;
	}

	public void setUpdatePendingAt(Date updatePendingAt) {
		this.updatePendingAt = updatePendingAt;
	}

	@Column(name = "update_pending_rp_status", length = 10)
	public String getUpdatePendingRpStatus() {
		return this.updatePendingRpStatus;
	}

	public void setUpdatePendingRpStatus(String updatePendingRpStatus) {
		this.updatePendingRpStatus = updatePendingRpStatus;
	}

	@Column(name = "from_ip", length = 20)
	public String getFromIp() {
		return this.fromIp;
	}

	public void setFromIp(String fromIp) {
		this.fromIp = fromIp;
	}

	@Column(name = "client_req_id", nullable = false, length = 50)
	public String getClientReqId() {
		return this.clientReqId;
	}

	public void setClientReqId(String clientReqId) {
		this.clientReqId = clientReqId;
	}

	@Column(name = "partner_req_id", nullable = false, length = 50)
	public String getPartnerReqId() {
		return this.partnerReqId;
	}

	public void setPartnerReqId(String partnerReqId) {
		this.partnerReqId = partnerReqId;
	}

	@Column(name = "provider_code", length = 10)
	public String getProviderCode() {
		return this.providerCode;
	}

	public void setProviderCode(String providerCode) {
		this.providerCode = providerCode;
	}

	@Column(name = "partner_full_body_rp", length = 1000)
	public String getPartnerFullBodyRp() {
		return this.partnerFullBodyRp;
	}

	public void setPartnerFullBodyRp(String partnerFullBodyRp) {
		this.partnerFullBodyRp = partnerFullBodyRp;
	}

	@Column(name = "merchant_id")
	public Integer getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(Integer merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "merchant_username", length = 50)
	public String getMerchantUsername() {
		return this.merchantUsername;
	}

	public void setMerchantUsername(String merchantUsername) {
		this.merchantUsername = merchantUsername;
	}

}
